import { Customer } from '@/types';

export const mockCustomers: Customer[] = [
  {
    id: 'cust-1',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@email.com',
    phone: '+1-555-0101',
    address: { street: '123 Main St', city: 'New York', stateProvince: 'New York', zipCode: '10001', country: 'USA' },
    idType: 'Driver License',
    idNumber: 'DL123456',
    registrationDate: '2024-01-15',
  },
  {
    id: 'cust-2',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@email.com',
    phone: '+1-555-0102',
    address: { street: '456 Oak Ave', city: 'Los Angeles', stateProvince: 'California', zipCode: '90001', country: 'USA' },
    idType: 'SSN',
    idNumber: '***-**-7890',
    registrationDate: '2024-02-20',
  },
  {
    id: 'cust-3',
    firstName: 'Robert',
    lastName: 'Johnson',
    email: 'robert.johnson@email.com',
    phone: '+1-555-0103',
    address: { street: '789 Pine Rd', city: 'Chicago', stateProvince: 'Illinois', zipCode: '60601', country: 'USA' },
    idType: 'Passport',
    idNumber: 'P12345678',
    registrationDate: '2024-03-10',
  },
  {
    id: 'cust-4',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'maria.garcia@email.com',
    phone: '+1-555-0104',
    address: { street: '321 Elm St', city: 'Houston', stateProvince: 'Texas', zipCode: '77001', country: 'USA' },
    idType: 'Driver License',
    idNumber: 'DL789012',
    registrationDate: '2024-04-05',
  },
  {
    id: 'cust-5',
    firstName: 'David',
    lastName: 'Martinez',
    email: 'david.martinez@email.com',
    phone: '+1-555-0105',
    address: { street: '654 Maple Dr', city: 'Phoenix', stateProvince: 'Arizona', zipCode: '85001', country: 'USA' },
    idType: 'SSN',
    idNumber: '***-**-3456',
    registrationDate: '2024-05-12',
  },
  {
    id: 'cust-6',
    firstName: 'Sarah',
    lastName: 'Anderson',
    email: 'sarah.anderson@email.com',
    phone: '+1-555-0106',
    address: { street: '987 Birch Ln', city: 'Philadelphia', stateProvince: 'Pennsylvania', zipCode: '19019', country: 'USA' },
    idType: 'Driver License',
    idNumber: 'DL345678',
    registrationDate: '2024-06-18',
  },
  {
    id: 'cust-7',
    firstName: 'Michael',
    lastName: 'Wilson',
    email: 'michael.wilson@email.com',
    phone: '+1-555-0107',
    address: { street: '147 Cedar St', city: 'San Antonio', stateProvince: 'Texas', zipCode: '78201', country: 'USA' },
    idType: 'Passport',
    idNumber: 'P87654321',
    registrationDate: '2024-07-22',
  },
  {
    id: 'cust-8',
    firstName: 'Emily',
    lastName: 'Taylor',
    email: 'emily.taylor@email.com',
    phone: '+1-555-0108',
    address: { street: '258 Spruce Ave', city: 'San Diego', stateProvince: 'California', zipCode: '92101', country: 'USA' },
    idType: 'SSN',
    idNumber: '***-**-9012',
    registrationDate: '2024-08-30',
  },
  {
    id: 'cust-9',
    firstName: 'Christopher',
    lastName: 'Thomas',
    email: 'christopher.thomas@email.com',
    phone: '+1-555-0109',
    address: { street: '369 Willow Rd', city: 'Dallas', stateProvince: 'Texas', zipCode: '75201', country: 'USA' },
    idType: 'Driver License',
    idNumber: 'DL901234',
    registrationDate: '2024-09-15',
  },
  {
    id: 'cust-10',
    firstName: 'Jessica',
    lastName: 'Moore',
    email: 'jessica.moore@email.com',
    phone: '+1-555-0110',
    address: { street: '741 Ash Blvd', city: 'San Jose', stateProvince: 'California', zipCode: '95101', country: 'USA' },
    idType: 'Passport',
    idNumber: 'P34567890',
    registrationDate: '2024-10-20',
  },
  {
    id: 'cust-11',
    firstName: 'Daniel',
    lastName: 'Jackson',
    email: 'daniel.jackson@email.com',
    phone: '+1-555-0111',
    address: { street: '852 Fir Way', city: 'Austin', stateProvince: 'Texas', zipCode: '73301', country: 'USA' },
    idType: 'Driver License',
    idNumber: 'DL567890',
    registrationDate: '2024-11-05',
  },
  {
    id: 'cust-12',
    firstName: 'Amanda',
    lastName: 'White',
    email: 'amanda.white@email.com',
    phone: '+1-555-0112',
    address: { street: '963 Poplar Dr', city: 'Jacksonville', stateProvince: 'Florida', zipCode: '32099', country: 'USA' },
    idType: 'SSN',
    idNumber: '***-**-5678',
    registrationDate: '2024-12-10',
  },
  {
    id: 'cust-13',
    firstName: 'Matthew',
    lastName: 'Harris',
    email: 'matthew.harris@email.com',
    phone: '+1-555-0113',
    address: { street: '159 Walnut St', city: 'Fort Worth', stateProvince: 'Texas', zipCode: '76101', country: 'USA' },
    idType: 'Passport',
    idNumber: 'P90123456',
    registrationDate: '2025-01-15',
  },
  {
    id: 'cust-14',
    firstName: 'Ashley',
    lastName: 'Martin',
    email: 'ashley.martin@email.com',
    phone: '+1-555-0114',
    address: { street: '357 Hickory Ln', city: 'Columbus', stateProvince: 'Ohio', zipCode: '43004', country: 'USA' },
    idType: 'Driver License',
    idNumber: 'DL234567',
    registrationDate: '2025-02-20',
  },
  {
    id: 'cust-15',
    firstName: 'Joshua',
    lastName: 'Thompson',
    email: 'joshua.thompson@email.com',
    phone: '+1-555-0115',
    address: { street: '753 Magnolia Ave', city: 'Charlotte', stateProvince: 'North Carolina', zipCode: '28201', country: 'USA' },
    idType: 'SSN',
    idNumber: '***-**-8901',
    registrationDate: '2025-03-05',
  },
  {
    id: 'cust-16',
    firstName: 'Sophia',
    lastName: 'Lee',
    email: 'sophia.lee@email.com',
    phone: '+1-416-555-0116',
    address: { street: '951 Bay Street', city: 'Toronto', stateProvince: 'Ontario', zipCode: 'M5G 2N8', country: 'Canada' },
    idType: 'SIN',
    idNumber: '***-***-789',
    registrationDate: '2025-04-10',
  },
  {
    id: 'cust-17',
    firstName: 'Alexander',
    lastName: 'Walker',
    email: 'alexander.walker@email.com',
    phone: '+1-555-0117',
    address: { street: '357 Chestnut Rd', city: 'San Francisco', stateProvince: 'California', zipCode: '94102', country: 'USA' },
    idType: 'Driver License',
    idNumber: 'DL890123',
    registrationDate: '2025-05-15',
  },
  {
    id: 'cust-18',
    firstName: 'Olivia',
    lastName: 'Hall',
    email: 'olivia.hall@email.com',
    phone: '+1-555-0118',
    address: { street: '159 Sycamore St', city: 'Indianapolis', stateProvince: 'Indiana', zipCode: '46201', country: 'USA' },
    idType: 'Passport',
    idNumber: 'P56789012',
    registrationDate: '2025-06-20',
  },
  {
    id: 'cust-19',
    firstName: 'Ryan',
    lastName: 'Allen',
    email: 'ryan.allen@email.com',
    phone: '+1-555-0119',
    address: { street: '753 Cypress Way', city: 'Seattle', stateProvince: 'Washington', zipCode: '98101', country: 'USA' },
    idType: 'Driver License',
    idNumber: 'DL456789',
    registrationDate: '2025-07-25',
  },
  {
    id: 'cust-20',
    firstName: 'Emma',
    lastName: 'Young',
    email: 'emma.young@email.com',
    phone: '+1-555-0120',
    address: { street: '951 Redwood Dr', city: 'Denver', stateProvince: 'Colorado', zipCode: '80201', country: 'USA' },
    idType: 'SSN',
    idNumber: '***-**-2345',
    registrationDate: '2025-08-30',
  },
];
