import { Employee } from '@/types';

export const mockEmployees: Employee[] = [
  // Managers for each hotel (40 hotels)
  {
    id: 'emp-1',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'james.wilson@marriott.com',
    address: { street: '123 Ocean Drive', city: 'Miami Beach', stateProvince: 'Florida', zipCode: '33139', country: 'USA' },
    ssnSin: '***-**-1234',
    role: 'Manager',
    hotelId: 'hotel-1',
  },
  {
    id: 'emp-2',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@marriott.com',
    address: { street: '456 Michigan Ave', city: 'Chicago', stateProvince: 'Illinois', zipCode: '60611', country: 'USA' },
    ssnSin: '***-**-2345',
    role: 'Manager',
    hotelId: 'hotel-2',
  },
  {
    id: 'emp-3',
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.brown@marriott.com',
    address: { street: '789 Broadway', city: 'New York', stateProvince: 'New York', zipCode: '10036', country: 'USA' },
    ssnSin: '***-**-3456',
    role: 'Manager',
    hotelId: 'hotel-3',
  },
  {
    id: 'emp-4',
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.davis@marriott.com',
    address: { street: '321 Sutter St', city: 'San Francisco', stateProvince: 'California', zipCode: '94108', country: 'USA' },
    ssnSin: '***-**-4567',
    role: 'Manager',
    hotelId: 'hotel-4',
  },
  {
    id: 'emp-5',
    firstName: 'David',
    lastName: 'Martinez',
    email: 'david.martinez@marriott.com',
    address: { street: '654 Seaport Blvd', city: 'Boston', stateProvince: 'Massachusetts', zipCode: '02210', country: 'USA' },
    ssnSin: '***-**-5678',
    role: 'Manager',
    hotelId: 'hotel-5',
  },
  {
    id: 'emp-6',
    firstName: 'Jennifer',
    lastName: 'Garcia',
    email: 'jennifer.garcia@marriott.com',
    address: { street: '987 Convention Dr', city: 'Las Vegas', stateProvince: 'Nevada', zipCode: '89109', country: 'USA' },
    ssnSin: '***-**-6789',
    role: 'Manager',
    hotelId: 'hotel-6',
  },
  {
    id: 'emp-7',
    firstName: 'Robert',
    lastName: 'Rodriguez',
    email: 'robert.rodriguez@marriott.com',
    address: { street: '147 Alaskan Way', city: 'Seattle', stateProvince: 'Washington', zipCode: '98121', country: 'USA' },
    ssnSin: '***-**-7890',
    role: 'Manager',
    hotelId: 'hotel-7',
  },
  {
    id: 'emp-8',
    firstName: 'Lisa',
    lastName: 'Wilson',
    email: 'lisa.wilson@marriott.com',
    address: { street: '258 Bay Street', city: 'Toronto', stateProvince: 'Ontario', zipCode: 'M5G 2L2', country: 'Canada' },
    ssnSin: '***-**-8901',
    role: 'Manager',
    hotelId: 'hotel-8',
  },
  {
    id: 'emp-9',
    firstName: 'Christopher',
    lastName: 'Lee',
    email: 'christopher.lee@hilton.com',
    address: { street: '369 Biscayne Blvd', city: 'Miami', stateProvince: 'Florida', zipCode: '33132', country: 'USA' },
    ssnSin: '***-**-9012',
    role: 'Manager',
    hotelId: 'hotel-9',
  },
  {
    id: 'emp-10',
    firstName: 'Amanda',
    lastName: 'Walker',
    email: 'amanda.walker@hilton.com',
    address: { street: '741 Michigan Ave', city: 'Chicago', stateProvince: 'Illinois', zipCode: '60605', country: 'USA' },
    ssnSin: '***-**-0123',
    role: 'Manager',
    hotelId: 'hotel-10',
  },
  {
    id: 'emp-11',
    firstName: 'Daniel',
    lastName: 'Harris',
    email: 'daniel.harris@hilton.com',
    address: { street: '852 6th Ave', city: 'New York', stateProvince: 'New York', zipCode: '10019', country: 'USA' },
    ssnSin: '***-**-1235',
    role: 'Manager',
    hotelId: 'hotel-11',
  },
  {
    id: 'emp-12',
    firstName: 'Michelle',
    lastName: 'Clark',
    email: 'michelle.clark@hilton.com',
    address: { street: '963 O\'Farrell St', city: 'San Francisco', stateProvince: 'California', zipCode: '94102', country: 'USA' },
    ssnSin: '***-**-2346',
    role: 'Manager',
    hotelId: 'hotel-12',
  },
  {
    id: 'emp-13',
    firstName: 'Matthew',
    lastName: 'Lewis',
    email: 'matthew.lewis@hilton.com',
    address: { street: '159 Park Plaza', city: 'Boston', stateProvince: 'Massachusetts', zipCode: '02116', country: 'USA' },
    ssnSin: '***-**-3457',
    role: 'Manager',
    hotelId: 'hotel-13',
  },
  {
    id: 'emp-14',
    firstName: 'Jessica',
    lastName: 'Robinson',
    email: 'jessica.robinson@hilton.com',
    address: { street: '753 Las Vegas Blvd', city: 'Las Vegas', stateProvince: 'Nevada', zipCode: '89109', country: 'USA' },
    ssnSin: '***-**-4568',
    role: 'Manager',
    hotelId: 'hotel-14',
  },
  {
    id: 'emp-15',
    firstName: 'Andrew',
    lastName: 'Young',
    email: 'andrew.young@hilton.com',
    address: { street: '951 International Blvd', city: 'Seattle', stateProvince: 'Washington', zipCode: '98188', country: 'USA' },
    ssnSin: '***-**-5679',
    role: 'Manager',
    hotelId: 'hotel-15',
  },
  {
    id: 'emp-16',
    firstName: 'Nicole',
    lastName: 'King',
    email: 'nicole.king@hilton.com',
    address: { street: '357 Richmond St W', city: 'Toronto', stateProvince: 'Ontario', zipCode: 'M5H 2L2', country: 'Canada' },
    ssnSin: '***-**-6780',
    role: 'Manager',
    hotelId: 'hotel-16',
  },
  {
    id: 'emp-17',
    firstName: 'Joshua',
    lastName: 'Wright',
    email: 'joshua.wright@hyatt.com',
    address: { street: '159 SE 2nd Ave', city: 'Miami', stateProvince: 'Florida', zipCode: '33131', country: 'USA' },
    ssnSin: '***-**-7891',
    role: 'Manager',
    hotelId: 'hotel-17',
  },
  {
    id: 'emp-18',
    firstName: 'Stephanie',
    lastName: 'Lopez',
    email: 'stephanie.lopez@hyatt.com',
    address: { street: '753 Wacker Dr', city: 'Chicago', stateProvince: 'Illinois', zipCode: '60601', country: 'USA' },
    ssnSin: '***-**-8902',
    role: 'Manager',
    hotelId: 'hotel-18',
  },
  {
    id: 'emp-19',
    firstName: 'Kevin',
    lastName: 'Hill',
    email: 'kevin.hill@hyatt.com',
    address: { street: '357 42nd St', city: 'New York', stateProvince: 'New York', zipCode: '10017', country: 'USA' },
    ssnSin: '***-**-9013',
    role: 'Manager',
    hotelId: 'hotel-19',
  },
  {
    id: 'emp-20',
    firstName: 'Rachel',
    lastName: 'Scott',
    email: 'rachel.scott@hyatt.com',
    address: { street: '951 Embarcadero', city: 'San Francisco', stateProvince: 'California', zipCode: '94111', country: 'USA' },
    ssnSin: '***-**-0124',
    role: 'Manager',
    hotelId: 'hotel-20',
  },
  {
    id: 'emp-21',
    firstName: 'Brandon',
    lastName: 'Green',
    email: 'brandon.green@hyatt.com',
    address: { street: '357 Lafayette Ave', city: 'Boston', stateProvince: 'Massachusetts', zipCode: '02111', country: 'USA' },
    ssnSin: '***-**-1236',
    role: 'Manager',
    hotelId: 'hotel-21',
  },
  {
    id: 'emp-22',
    firstName: 'Lauren',
    lastName: 'Adams',
    email: 'lauren.adams@hyatt.com',
    address: { street: '753 Montelago Blvd', city: 'Henderson', stateProvince: 'Nevada', zipCode: '89011', country: 'USA' },
    ssnSin: '***-**-2347',
    role: 'Manager',
    hotelId: 'hotel-22',
  },
  {
    id: 'emp-23',
    firstName: 'Ryan',
    lastName: 'Baker',
    email: 'ryan.baker@hyatt.com',
    address: { street: '159 Howell St', city: 'Seattle', stateProvince: 'Washington', zipCode: '98101', country: 'USA' },
    ssnSin: '***-**-3458',
    role: 'Manager',
    hotelId: 'hotel-23',
  },
  {
    id: 'emp-24',
    firstName: 'Megan',
    lastName: 'Nelson',
    email: 'megan.nelson@hyatt.com',
    address: { street: '753 King St W', city: 'Toronto', stateProvince: 'Ontario', zipCode: 'M5V 1J9', country: 'Canada' },
    ssnSin: '***-**-4569',
    role: 'Manager',
    hotelId: 'hotel-24',
  },
  {
    id: 'emp-25',
    firstName: 'Justin',
    lastName: 'Carter',
    email: 'justin.carter@ihg.com',
    address: { street: '357 Chopin Plaza', city: 'Miami', stateProvince: 'Florida', zipCode: '33131', country: 'USA' },
    ssnSin: '***-**-5670',
    role: 'Manager',
    hotelId: 'hotel-25',
  },
  {
    id: 'emp-26',
    firstName: 'Kimberly',
    lastName: 'Mitchell',
    email: 'kimberly.mitchell@ihg.com',
    address: { street: '159 Michigan Ave', city: 'Chicago', stateProvince: 'Illinois', zipCode: '60611', country: 'USA' },
    ssnSin: '***-**-6781',
    role: 'Manager',
    hotelId: 'hotel-26',
  },
  {
    id: 'emp-27',
    firstName: 'Timothy',
    lastName: 'Perez',
    email: 'timothy.perez@ihg.com',
    address: { street: '753 44th St', city: 'New York', stateProvince: 'New York', zipCode: '10036', country: 'USA' },
    ssnSin: '***-**-7892',
    role: 'Manager',
    hotelId: 'hotel-27',
  },
  {
    id: 'emp-28',
    firstName: 'Heather',
    lastName: 'Roberts',
    email: 'heather.roberts@ihg.com',
    address: { street: '357 California St', city: 'San Francisco', stateProvince: 'California', zipCode: '94108', country: 'USA' },
    ssnSin: '***-**-8903',
    role: 'Manager',
    hotelId: 'hotel-28',
  },
  {
    id: 'emp-29',
    firstName: 'Jason',
    lastName: 'Turner',
    email: 'jason.turner@ihg.com',
    address: { street: '159 Atlantic Ave', city: 'Boston', stateProvince: 'Massachusetts', zipCode: '02210', country: 'USA' },
    ssnSin: '***-**-9014',
    role: 'Manager',
    hotelId: 'hotel-29',
  },
  {
    id: 'emp-30',
    firstName: 'Samantha',
    lastName: 'Phillips',
    email: 'samantha.phillips@ihg.com',
    address: { street: '753 Paradise Rd', city: 'Las Vegas', stateProvince: 'Nevada', zipCode: '89169', country: 'USA' },
    ssnSin: '***-**-0125',
    role: 'Manager',
    hotelId: 'hotel-30',
  },
  {
    id: 'emp-31',
    firstName: 'Nathan',
    lastName: 'Campbell',
    email: 'nathan.campbell@ihg.com',
    address: { street: '357 Marion St', city: 'Seattle', stateProvince: 'Washington', zipCode: '98104', country: 'USA' },
    ssnSin: '***-**-1237',
    role: 'Manager',
    hotelId: 'hotel-31',
  },
  {
    id: 'emp-32',
    firstName: 'Ashley',
    lastName: 'Parker',
    email: 'ashley.parker@ihg.com',
    address: { street: '159 Front St W', city: 'Toronto', stateProvince: 'Ontario', zipCode: 'M5V 2X3', country: 'Canada' },
    ssnSin: '***-**-2348',
    role: 'Manager',
    hotelId: 'hotel-32',
  },
  {
    id: 'emp-33',
    firstName: 'Benjamin',
    lastName: 'Evans',
    email: 'benjamin.evans@fourseasons.com',
    address: { street: '753 Brickell Ave', city: 'Miami', stateProvince: 'Florida', zipCode: '33131', country: 'USA' },
    ssnSin: '***-**-3459',
    role: 'Manager',
    hotelId: 'hotel-33',
  },
  {
    id: 'emp-34',
    firstName: 'Christina',
    lastName: 'Edwards',
    email: 'christina.edwards@fourseasons.com',
    address: { street: '357 Delaware Pl', city: 'Chicago', stateProvince: 'Illinois', zipCode: '60611', country: 'USA' },
    ssnSin: '***-**-4570',
    role: 'Manager',
    hotelId: 'hotel-34',
  },
  {
    id: 'emp-35',
    firstName: 'Jonathan',
    lastName: 'Collins',
    email: 'jonathan.collins@fourseasons.com',
    address: { street: '159 Barclay St', city: 'New York', stateProvince: 'New York', zipCode: '10007', country: 'USA' },
    ssnSin: '***-**-5671',
    role: 'Manager',
    hotelId: 'hotel-35',
  },
  {
    id: 'emp-36',
    firstName: 'Rebecca',
    lastName: 'Stewart',
    email: 'rebecca.stewart@fourseasons.com',
    address: { street: '753 University Ave', city: 'East Palo Alto', stateProvince: 'California', zipCode: '94303', country: 'USA' },
    ssnSin: '***-**-6782',
    role: 'Manager',
    hotelId: 'hotel-36',
  },
  {
    id: 'emp-37',
    firstName: 'Tyler',
    lastName: 'Morris',
    email: 'tyler.morris@fourseasons.com',
    address: { street: '357 Dalton St', city: 'Boston', stateProvince: 'Massachusetts', zipCode: '02199', country: 'USA' },
    ssnSin: '***-**-7893',
    role: 'Manager',
    hotelId: 'hotel-37',
  },
  {
    id: 'emp-38',
    firstName: 'Victoria',
    lastName: 'Rogers',
    email: 'victoria.rogers@fourseasons.com',
    address: { street: '159 Las Vegas Blvd S', city: 'Las Vegas', stateProvince: 'Nevada', zipCode: '89119', country: 'USA' },
    ssnSin: '***-**-8904',
    role: 'Manager',
    hotelId: 'hotel-38',
  },
  {
    id: 'emp-39',
    firstName: 'Zachary',
    lastName: 'Reed',
    email: 'zachary.reed@fourseasons.com',
    address: { street: '753 Union St', city: 'Seattle', stateProvince: 'Washington', zipCode: '98101', country: 'USA' },
    ssnSin: '***-**-9015',
    role: 'Manager',
    hotelId: 'hotel-39',
  },
  {
    id: 'emp-40',
    firstName: 'Olivia',
    lastName: 'Cook',
    email: 'olivia.cook@fourseasons.com',
    address: { street: '357 Yorkville Ave', city: 'Toronto', stateProvince: 'Ontario', zipCode: 'M4W 0A4', country: 'Canada' },
    ssnSin: '***-**-0126',
    role: 'Manager',
    hotelId: 'hotel-40',
  },
  // Additional staff (Receptionists, etc.)
  {
    id: 'emp-41',
    firstName: 'Emma',
    lastName: 'Morgan',
    email: 'emma.morgan@marriott.com',
    address: { street: '555 Ocean Drive', city: 'Miami Beach', stateProvince: 'Florida', zipCode: '33139', country: 'USA' },
    ssnSin: '***-**-1238',
    role: 'Receptionist',
    hotelId: 'hotel-1',
  },
  {
    id: 'emp-42',
    firstName: 'Liam',
    lastName: 'Bell',
    email: 'liam.bell@hilton.com',
    address: { street: '777 Biscayne Blvd', city: 'Miami', stateProvince: 'Florida', zipCode: '33132', country: 'USA' },
    ssnSin: '***-**-2349',
    role: 'Receptionist',
    hotelId: 'hotel-9',
  },
];
