import { Hotel } from '@/types';

export const mockHotels: Hotel[] = [
  // Marriott Hotels
  {
    id: 'hotel-1',
    name: 'Marriott Miami Beach',
    chainId: 'chain-1',
    category: 5,
    address: { street: '1201 Ocean Drive', city: 'Miami Beach', stateProvince: 'Florida', zipCode: '33139', country: 'USA' },
    contactEmail: 'miamibeach@marriott.com',
    contactPhone: '+1-305-538-4000',
    numberOfRooms: 5,
    managerId: 'emp-1',
  },
  {
    id: 'hotel-2',
    name: 'Marriott Downtown Chicago',
    chainId: 'chain-1',
    category: 4,
    address: { street: '540 North Michigan Avenue', city: 'Chicago', stateProvince: 'Illinois', zipCode: '60611', country: 'USA' },
    contactEmail: 'chicago@marriott.com',
    contactPhone: '+1-312-836-0100',
    numberOfRooms: 5,
    managerId: 'emp-2',
  },
  {
    id: 'hotel-3',
    name: 'Marriott Times Square',
    chainId: 'chain-1',
    category: 5,
    address: { street: '1535 Broadway', city: 'New York', stateProvince: 'New York', zipCode: '10036', country: 'USA' },
    contactEmail: 'timessquare@marriott.com',
    contactPhone: '+1-212-398-1900',
    numberOfRooms: 5,
    managerId: 'emp-3',
  },
  {
    id: 'hotel-4',
    name: 'Marriott San Francisco',
    chainId: 'chain-1',
    category: 4,
    address: { street: '480 Sutter Street', city: 'San Francisco', stateProvince: 'California', zipCode: '94108', country: 'USA' },
    contactEmail: 'sanfrancisco@marriott.com',
    contactPhone: '+1-415-398-8900',
    numberOfRooms: 5,
    managerId: 'emp-4',
  },
  {
    id: 'hotel-5',
    name: 'Marriott Boston Harbor',
    chainId: 'chain-1',
    category: 3,
    address: { street: '200 Seaport Boulevard', city: 'Boston', stateProvince: 'Massachusetts', zipCode: '02210', country: 'USA' },
    contactEmail: 'boston@marriott.com',
    contactPhone: '+1-617-385-4000',
    numberOfRooms: 5,
    managerId: 'emp-5',
  },
  {
    id: 'hotel-6',
    name: 'Marriott Las Vegas',
    chainId: 'chain-1',
    category: 4,
    address: { street: '325 Convention Center Drive', city: 'Las Vegas', stateProvince: 'Nevada', zipCode: '89109', country: 'USA' },
    contactEmail: 'lasvegas@marriott.com',
    contactPhone: '+1-702-650-2000',
    numberOfRooms: 5,
    managerId: 'emp-6',
  },
  {
    id: 'hotel-7',
    name: 'Marriott Seattle Waterfront',
    chainId: 'chain-1',
    category: 3,
    address: { street: '2100 Alaskan Way', city: 'Seattle', stateProvince: 'Washington', zipCode: '98121', country: 'USA' },
    contactEmail: 'seattle@marriott.com',
    contactPhone: '+1-206-443-5000',
    numberOfRooms: 5,
    managerId: 'emp-7',
  },
  {
    id: 'hotel-8',
    name: 'Marriott Toronto Downtown',
    chainId: 'chain-1',
    category: 4,
    address: { street: '525 Bay Street', city: 'Toronto', stateProvince: 'Ontario', zipCode: 'M5G 2L2', country: 'Canada' },
    contactEmail: 'toronto@marriott.com',
    contactPhone: '+1-416-597-9200',
    numberOfRooms: 5,
    managerId: 'emp-8',
  },

  // Hilton Hotels
  {
    id: 'hotel-9',
    name: 'Hilton Miami Downtown',
    chainId: 'chain-2',
    category: 4,
    address: { street: '1601 Biscayne Boulevard', city: 'Miami', stateProvince: 'Florida', zipCode: '33132', country: 'USA' },
    contactEmail: 'miami@hilton.com',
    contactPhone: '+1-305-374-0000',
    numberOfRooms: 5,
    managerId: 'emp-9',
  },
  {
    id: 'hotel-10',
    name: 'Hilton Chicago',
    chainId: 'chain-2',
    category: 5,
    address: { street: '720 South Michigan Avenue', city: 'Chicago', stateProvince: 'Illinois', zipCode: '60605', country: 'USA' },
    contactEmail: 'chicago@hilton.com',
    contactPhone: '+1-312-922-4400',
    numberOfRooms: 5,
    managerId: 'emp-10',
  },
  {
    id: 'hotel-11',
    name: 'Hilton Midtown Manhattan',
    chainId: 'chain-2',
    category: 4,
    address: { street: '1335 Avenue of the Americas', city: 'New York', stateProvince: 'New York', zipCode: '10019', country: 'USA' },
    contactEmail: 'midtown@hilton.com',
    contactPhone: '+1-212-586-7000',
    numberOfRooms: 5,
    managerId: 'emp-11',
  },
  {
    id: 'hotel-12',
    name: 'Hilton San Francisco Union Square',
    chainId: 'chain-2',
    category: 5,
    address: { street: '333 O\'Farrell Street', city: 'San Francisco', stateProvince: 'California', zipCode: '94102', country: 'USA' },
    contactEmail: 'unionsquare@hilton.com',
    contactPhone: '+1-415-771-1400',
    numberOfRooms: 5,
    managerId: 'emp-12',
  },
  {
    id: 'hotel-13',
    name: 'Hilton Boston Park Plaza',
    chainId: 'chain-2',
    category: 4,
    address: { street: '50 Park Plaza', city: 'Boston', stateProvince: 'Massachusetts', zipCode: '02116', country: 'USA' },
    contactEmail: 'parkplaza@hilton.com',
    contactPhone: '+1-617-426-2000',
    numberOfRooms: 5,
    managerId: 'emp-13',
  },
  {
    id: 'hotel-14',
    name: 'Hilton Grand Vacations Las Vegas',
    chainId: 'chain-2',
    category: 3,
    address: { street: '2650 Las Vegas Boulevard South', city: 'Las Vegas', stateProvince: 'Nevada', zipCode: '89109', country: 'USA' },
    contactEmail: 'grandvacations@hilton.com',
    contactPhone: '+1-702-946-9000',
    numberOfRooms: 5,
    managerId: 'emp-14',
  },
  {
    id: 'hotel-15',
    name: 'Hilton Seattle Airport',
    chainId: 'chain-2',
    category: 3,
    address: { street: '17620 International Boulevard', city: 'Seattle', stateProvince: 'Washington', zipCode: '98188', country: 'USA' },
    contactEmail: 'seattleairport@hilton.com',
    contactPhone: '+1-206-244-4800',
    numberOfRooms: 5,
    managerId: 'emp-15',
  },
  {
    id: 'hotel-16',
    name: 'Hilton Toronto',
    chainId: 'chain-2',
    category: 4,
    address: { street: '145 Richmond Street West', city: 'Toronto', stateProvince: 'Ontario', zipCode: 'M5H 2L2', country: 'Canada' },
    contactEmail: 'toronto@hilton.com',
    contactPhone: '+1-416-869-3456',
    numberOfRooms: 5,
    managerId: 'emp-16',
  },

  // Hyatt Hotels
  {
    id: 'hotel-17',
    name: 'Hyatt Regency Miami',
    chainId: 'chain-3',
    category: 4,
    address: { street: '400 SE 2nd Avenue', city: 'Miami', stateProvince: 'Florida', zipCode: '33131', country: 'USA' },
    contactEmail: 'miami@hyatt.com',
    contactPhone: '+1-305-358-1234',
    numberOfRooms: 5,
    managerId: 'emp-17',
  },
  {
    id: 'hotel-18',
    name: 'Hyatt Regency Chicago',
    chainId: 'chain-3',
    category: 5,
    address: { street: '151 East Wacker Drive', city: 'Chicago', stateProvince: 'Illinois', zipCode: '60601', country: 'USA' },
    contactEmail: 'chicago@hyatt.com',
    contactPhone: '+1-312-565-1234',
    numberOfRooms: 5,
    managerId: 'emp-18',
  },
  {
    id: 'hotel-19',
    name: 'Hyatt Grand Central New York',
    chainId: 'chain-3',
    category: 4,
    address: { street: '109 East 42nd Street', city: 'New York', stateProvince: 'New York', zipCode: '10017', country: 'USA' },
    contactEmail: 'grandcentral@hyatt.com',
    contactPhone: '+1-212-883-1234',
    numberOfRooms: 5,
    managerId: 'emp-19',
  },
  {
    id: 'hotel-20',
    name: 'Hyatt Regency San Francisco',
    chainId: 'chain-3',
    category: 5,
    address: { street: '5 Embarcadero Center', city: 'San Francisco', stateProvince: 'California', zipCode: '94111', country: 'USA' },
    contactEmail: 'sanfrancisco@hyatt.com',
    contactPhone: '+1-415-788-1234',
    numberOfRooms: 5,
    managerId: 'emp-20',
  },
  {
    id: 'hotel-21',
    name: 'Hyatt Regency Boston',
    chainId: 'chain-3',
    category: 4,
    address: { street: '1 Avenue de Lafayette', city: 'Boston', stateProvince: 'Massachusetts', zipCode: '02111', country: 'USA' },
    contactEmail: 'boston@hyatt.com',
    contactPhone: '+1-617-912-1234',
    numberOfRooms: 5,
    managerId: 'emp-21',
  },
  {
    id: 'hotel-22',
    name: 'Hyatt Regency Lake Las Vegas',
    chainId: 'chain-3',
    category: 4,
    address: { street: '101 Montelago Boulevard', city: 'Henderson', stateProvince: 'Nevada', zipCode: '89011', country: 'USA' },
    contactEmail: 'lakelasvegas@hyatt.com',
    contactPhone: '+1-702-567-1234',
    numberOfRooms: 5,
    managerId: 'emp-22',
  },
  {
    id: 'hotel-23',
    name: 'Hyatt Regency Seattle',
    chainId: 'chain-3',
    category: 3,
    address: { street: '808 Howell Street', city: 'Seattle', stateProvince: 'Washington', zipCode: '98101', country: 'USA' },
    contactEmail: 'seattle@hyatt.com',
    contactPhone: '+1-206-973-1234',
    numberOfRooms: 5,
    managerId: 'emp-23',
  },
  {
    id: 'hotel-24',
    name: 'Hyatt Regency Toronto',
    chainId: 'chain-3',
    category: 4,
    address: { street: '370 King Street West', city: 'Toronto', stateProvince: 'Ontario', zipCode: 'M5V 1J9', country: 'Canada' },
    contactEmail: 'toronto@hyatt.com',
    contactPhone: '+1-416-343-1234',
    numberOfRooms: 5,
    managerId: 'emp-24',
  },

  // InterContinental Hotels
  {
    id: 'hotel-25',
    name: 'InterContinental Miami',
    chainId: 'chain-4',
    category: 5,
    address: { street: '100 Chopin Plaza', city: 'Miami', stateProvince: 'Florida', zipCode: '33131', country: 'USA' },
    contactEmail: 'miami@ihg.com',
    contactPhone: '+1-305-577-1000',
    numberOfRooms: 5,
    managerId: 'emp-25',
  },
  {
    id: 'hotel-26',
    name: 'InterContinental Chicago',
    chainId: 'chain-4',
    category: 5,
    address: { street: '505 North Michigan Avenue', city: 'Chicago', stateProvince: 'Illinois', zipCode: '60611', country: 'USA' },
    contactEmail: 'chicago@ihg.com',
    contactPhone: '+1-312-944-4100',
    numberOfRooms: 5,
    managerId: 'emp-26',
  },
  {
    id: 'hotel-27',
    name: 'InterContinental New York Times Square',
    chainId: 'chain-4',
    category: 5,
    address: { street: '300 West 44th Street', city: 'New York', stateProvince: 'New York', zipCode: '10036', country: 'USA' },
    contactEmail: 'timessquare@ihg.com',
    contactPhone: '+1-212-803-4500',
    numberOfRooms: 5,
    managerId: 'emp-27',
  },
  {
    id: 'hotel-28',
    name: 'InterContinental Mark Hopkins San Francisco',
    chainId: 'chain-4',
    category: 5,
    address: { street: '999 California Street', city: 'San Francisco', stateProvince: 'California', zipCode: '94108', country: 'USA' },
    contactEmail: 'markhopkins@ihg.com',
    contactPhone: '+1-415-392-3434',
    numberOfRooms: 5,
    managerId: 'emp-28',
  },
  {
    id: 'hotel-29',
    name: 'InterContinental Boston',
    chainId: 'chain-4',
    category: 4,
    address: { street: '510 Atlantic Avenue', city: 'Boston', stateProvince: 'Massachusetts', zipCode: '02210', country: 'USA' },
    contactEmail: 'boston@ihg.com',
    contactPhone: '+1-617-747-1000',
    numberOfRooms: 5,
    managerId: 'emp-29',
  },
  {
    id: 'hotel-30',
    name: 'InterContinental Alliance Resorts Las Vegas',
    chainId: 'chain-4',
    category: 3,
    address: { street: '3500 Paradise Road', city: 'Las Vegas', stateProvince: 'Nevada', zipCode: '89169', country: 'USA' },
    contactEmail: 'alliance@ihg.com',
    contactPhone: '+1-702-507-7777',
    numberOfRooms: 5,
    managerId: 'emp-30',
  },
  {
    id: 'hotel-31',
    name: 'InterContinental Seattle',
    chainId: 'chain-4',
    category: 4,
    address: { street: '83 Marion Street', city: 'Seattle', stateProvince: 'Washington', zipCode: '98104', country: 'USA' },
    contactEmail: 'seattle@ihg.com',
    contactPhone: '+1-206-264-1000',
    numberOfRooms: 5,
    managerId: 'emp-31',
  },
  {
    id: 'hotel-32',
    name: 'InterContinental Toronto Centre',
    chainId: 'chain-4',
    category: 5,
    address: { street: '225 Front Street West', city: 'Toronto', stateProvince: 'Ontario', zipCode: 'M5V 2X3', country: 'Canada' },
    contactEmail: 'torontocentre@ihg.com',
    contactPhone: '+1-416-597-1400',
    numberOfRooms: 5,
    managerId: 'emp-32',
  },

  // Four Seasons Hotels
  {
    id: 'hotel-33',
    name: 'Four Seasons Miami',
    chainId: 'chain-5',
    category: 5,
    address: { street: '1435 Brickell Avenue', city: 'Miami', stateProvince: 'Florida', zipCode: '33131', country: 'USA' },
    contactEmail: 'miami@fourseasons.com',
    contactPhone: '+1-305-358-3535',
    numberOfRooms: 5,
    managerId: 'emp-33',
  },
  {
    id: 'hotel-34',
    name: 'Four Seasons Chicago',
    chainId: 'chain-5',
    category: 5,
    address: { street: '120 East Delaware Place', city: 'Chicago', stateProvince: 'Illinois', zipCode: '60611', country: 'USA' },
    contactEmail: 'chicago@fourseasons.com',
    contactPhone: '+1-312-280-8800',
    numberOfRooms: 5,
    managerId: 'emp-34',
  },
  {
    id: 'hotel-35',
    name: 'Four Seasons New York Downtown',
    chainId: 'chain-5',
    category: 5,
    address: { street: '27 Barclay Street', city: 'New York', stateProvince: 'New York', zipCode: '10007', country: 'USA' },
    contactEmail: 'downtown@fourseasons.com',
    contactPhone: '+1-646-880-1999',
    numberOfRooms: 5,
    managerId: 'emp-35',
  },
  {
    id: 'hotel-36',
    name: 'Four Seasons Silicon Valley',
    chainId: 'chain-5',
    category: 5,
    address: { street: '2050 University Avenue', city: 'East Palo Alto', stateProvince: 'California', zipCode: '94303', country: 'USA' },
    contactEmail: 'siliconvalley@fourseasons.com',
    contactPhone: '+1-650-566-1200',
    numberOfRooms: 5,
    managerId: 'emp-36',
  },
  {
    id: 'hotel-37',
    name: 'Four Seasons One Dalton Boston',
    chainId: 'chain-5',
    category: 5,
    address: { street: '1 Dalton Street', city: 'Boston', stateProvince: 'Massachusetts', zipCode: '02199', country: 'USA' },
    contactEmail: 'onedalton@fourseasons.com',
    contactPhone: '+1-617-447-3600',
    numberOfRooms: 5,
    managerId: 'emp-37',
  },
  {
    id: 'hotel-38',
    name: 'Four Seasons Las Vegas',
    chainId: 'chain-5',
    category: 5,
    address: { street: '3960 Las Vegas Boulevard South', city: 'Las Vegas', stateProvince: 'Nevada', zipCode: '89119', country: 'USA' },
    contactEmail: 'lasvegas@fourseasons.com',
    contactPhone: '+1-702-632-5000',
    numberOfRooms: 5,
    managerId: 'emp-38',
  },
  {
    id: 'hotel-39',
    name: 'Four Seasons Seattle',
    chainId: 'chain-5',
    category: 5,
    address: { street: '99 Union Street', city: 'Seattle', stateProvince: 'Washington', zipCode: '98101', country: 'USA' },
    contactEmail: 'seattle@fourseasons.com',
    contactPhone: '+1-206-749-7000',
    numberOfRooms: 5,
    managerId: 'emp-39',
  },
  {
    id: 'hotel-40',
    name: 'Four Seasons Toronto',
    chainId: 'chain-5',
    category: 5,
    address: { street: '60 Yorkville Avenue', city: 'Toronto', stateProvince: 'Ontario', zipCode: 'M4W 0A4', country: 'Canada' },
    contactEmail: 'toronto@fourseasons.com',
    contactPhone: '+1-416-964-0411',
    numberOfRooms: 5,
    managerId: 'emp-40',
  },
];
